### ISSUE TITLE
M1 mac 版 0.20.0 の vvppp のファイル名が他と一致しておらず、公式サイトからダウンロードできない

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox_nemo_engine#10]
## 不具合の内容

M1 mac 版 0.20.0 の vvppp のファイル名が他と一致しておらず、公式サイトからダウンロードできない

公式サイトからリンクされているURL：https://github.com/VOICEVOX/voicevox_nemo_engine/releases/download/0.20.0/voicevox_engine-macos-arm64-0.20.0.vvppp
実際にRelease に上がってるURL: https://github.com/VOICEVOX/voicevox_nemo_engine/releases/download/0.20.0/voicevox_engine-macos-arm64-0.20.0.001.vvppp

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

一応すでにmainブランチでは解決していて、あとは次のバージョンをリリースすれば自動的に解決する予定です 🙇 
そろそろリリース予定なので、もうしばらくだけでお待ちいただければと･･･！！

**Comment by raa0121** [comment]
ユーザがダウンロードできないので、Release に正しいファイル名の vvppp をアップロードすると良いと思います。

**Comment by Hiroshiba** [comment]
バージョン0.21から根本解決できたはずなのでクローズします！
ご報告ありがとうございました！！
